steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', './sonarqube/Dockerfile' ,'--tag=asia-south1-docker.pkg.dev/jmc-devsecops/hello-test/sonar-scanner:${_SONARQUBE_SCANNER_CLI_VERSION}', '--tag=asia-south1-docker.pkg.dev/jmc-devsecops/hello-test/sonar-scanner:latest', './sonarqube']

  images: 
  - 'asia-south1-docker.pkg.dev/jmc-devsecops/hello-test/sonar-scanner:latest'
  - 'asia-south1-docker.pkg.dev/jmc-devsecops/hello-test/sonar-scanner:${_SONARQUBE_SCANNER_CLI_VERSION}'
#   args:
#   - '-v'  # Verbose output
#   - '-o'  # Set SonarCloud organization
#     value: sonarcloud
#    Replace with your organization
#   - '-p'  # Set SonarCloud project
#     value: SONAR_TOKEN  # Replace with your project name
#   - '-t'  # Set SonarCloud token (use Secret Manager)
#     env:   $SONAR_TOKEN
#   - '-b'  # Set project base directory
#     path: 'your/project/base/directory'  # Replace with your path

# substitutions:
#   _PROJECT_ID: jmc-devsecops

# secrets:
#   - secretEnv: SONAR_TOKEN
#     projectId: jmc-devsecops
#     secretName: sonarcloud-token  # Replace with your secret name

tags: ['sonarcloud']
substitutions:
  _SONARQUBE_SCANNER_CLI_VERSION: 5.0.1